debug: true
server:
  port: 8090
  servlet: 
    context-path: /SpringFunction
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_system?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qds553446792
    max-idle: 10
    min-idle: 5
  output:
    ansi: 
      enabled: detect
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-page: com.example.demo.mapper
  
logging:
  pattern: 
    console: '%clr(%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n){blue}'
  file:
    path: /log
    name: info.log
  max-size: 1GB
  max-history: 3
